### ISSUE TITLE
에르네스트모드 버그 리폿합니다.

### ISSUE THREAD

**Issue by syleeee** [wan2land/unchartedwaters2#17]
1. 추가 도시들 지역이 잘못 설정 되어있음
캄팔라 - 지중해
누마즈 - 지중해
(인도 동편의 스토리도시(이름이...)는 미국으로 설정 되어있음)

2. 변경되어야할 도시이름이 그대로
캘커타 --> 코지코드여야 하나 캘커타 그대로

3.스토리진행중 필수 아이템 판매하지 않음
캘커타에서 나타라쟈 판매하지않음 (공작깃털부채를 사면 스토리진행 가능)
누마즈에서 주스 팔지 않음

4.엔딩이후 발견되어야할 오귀니아가 초반부터 발견됨

-------------
다른 모드 혹은 일반판과 파일을 혹시 공유하나요? 
정확한 원인은 모르겠지만 제 생각엔 충돌에 의한 오류로 보입니다.

**Comment by wan2land** [comment]
파일은 다 분리해서 넣어놓긴 했는데, 제가 잘못 넣었을 수 있겠네요. :-) 정상적으로 동작하는 에르네스트모드 파일을 넣으면 바로 고쳐질것으로 예상됩니다.

[https://github.com/wan2land/unchartedwater2/tree/master/game](https://github.com/wan2land/unchartedwater2/tree/master/game)

요 경로에 파일 교체해서 풀리퀘스트 가능하실까요? :-)

**Comment by ZeniusZerin** [comment]
교체 권한이 없다고 뜨는데 직접 해주셔야 될거 같습니다.
아직도 3번때문에 진행이 안됩니다.

**Comment by bkshinhy** [comment]
게임 첫실행시 스타트 게임을 해야 버그가 안걸립니다. 
로드게임해서 세이브 파일 로드하면 저 버그 걸립니다.
지우고 다시 깔아 첫 실행시 스타트 게임을 하세요.
