### ISSUE TITLE
혹시 영문판도 링크가 가능할까요? 

### ISSUE THREAD

**Issue by rubsave** [wan2land/unchartedwaters2#28]
좋은 프로그램 만들어주셔서 감사합니다.

혹시 영문판도 같이 링크 가능할까요 ^^?
한글은 너무 잘 제공해주셔서 좋은데 외국사이트는 찾아봐도 영문판은 아직 없더라구요..
혹시 되시면 부탁드립니다. 

항상 재미있게 하고 있고 감사드립니다.

**Comment by wan2land** [comment]
[https://archive.org/details/msdos_Uncharted_Waters_2_-_New_Horizons_1995](https://archive.org/details/msdos_Uncharted_Waters_2_-_New_Horizons_1995)

영문판은 요기에서도 할 수 있습니다! 🙂
