### ISSUE TITLE
대항해시대 외전 문의 (or 요청) 드립니다

### ISSUE THREAD

**Issue by nihonmovie** [wan2land/unchartedwaters2#30]
대항해시대 외전 (밀란다, 살바도르 편) 추가하실 계획은 없으신가요?

덕분에 즐겁게 게임하고 있습니다.
감사합니다.

**Comment by wan2land** [comment]
계획있습니다. 🙂
윈도우기반의게임인지라 근시일내에는 힘들어보입니다.
