### ISSUE TITLE
선생님 혹시... 

### ISSUE THREAD

**Issue by cox-rnd-hslee** [wan2land/unchartedwaters2#32]
안녕하세요 선생님. 
선생님 덕분에 폰으로도 알차게 대2를 할 수 있어서 좋았습니다.

혹시,, 영걸전이나 와룡전도 js-box로 구동 할 수 있나요?
애네들은 마우스 기반이라 터치로 해야 할 거 같은데

제가 어떻게 비벼볼려고 했지만 능력이 딸려서 감도 안오는군요 ㅠ

**Comment by wan2land** [comment]
제가 한번도 해보지 못한 게임은 제대로 돌아가는지 테스트할 방법이 없기 때문에 비슷한 프로젝트를 진행할 의향이 없습니다..

죄송합니다.
