### ISSUE TITLE
불러오기 누르면 창이 계속 닫히는데 어떤문제일까요?

### ISSUE THREAD

**Issue by hack2791** [wan2land/unchartedwaters2#34]
안녕하세요
세이브 파일을 불러오려고 불러오기를 누르면 처음에 몇번은 잘 됐는데 그 후론 
불러오기 누르면 세이브파일 선택하는 창이 열렸다 금방 닫힙니다.
새로 다른 브라우져를 설치해서 해도 처음 몇번은 열리는데 
그 후 계속 불러오기 창이 자동으로 닫힙니다. 물론 그 브라우져 다시 지우고 다시 설치해도 이제는 안되네요

**Comment by wan2land** [comment]
음.. 짐작되는 상황자체가 없습니다.

최근 0.4 업데이트 하면서 프레임워크를 업데이트하였는데 변경된 후에도 같은 문제가 발생한다면 다시 이슈 남겨주시면 감사하겠습니다!

다음 이슈 남겨주실 때 브라우저와 스크린샷도 함께 올려주시면 해당 증상 파악에 도움이 될거 같습니다!
